### PR TITLE
add: preProcess and postProcess functionality

### PR DESCRIPTION
**Pull request by prasannavl**
Currently, with most options, it's either take what react-snap does, or you get nothing. For instance, `removeScripts` remove every single script. `removeStyles` removes every single style. There's no way to customise this in anyway. Similarly, I've also needed a `defer` scripts functionality before (PR: https://github.com/stereobooster/react-snap/pull/169) but it didn't quite fit in nicely. 

This solves all these problem by being able to any custom functionality to modify the output as desired by directly using chrome's  `puppeteer`. This also helps moving all features as plugins and helps to easily experiment and add/remove features to react-snap.

### CODE REVIEW

**Comment by prasannavl** [comment]
Example usage: 

```js
// snap.js

const url = require("url");
const { run } = require("react-snap");
const fs = require("fs-extra");
const path = require("path");

async function snap() {
    process.chdir(path.resolve(path.join(__dirname, "./../")));
    run({
        publicPath: "/",
        preProcess: (snappy) => {
            return removeScriptTagsWithSrcAttribute(snappy)
        },
    });
}

async function runAsync() {
    await snap();
    process.once("beforeExit", () => {
        fs.unlink("./build/200.html");
        fs.unlink("./build/404.html");
    });
}

const deferScriptTags = ({ page }) => {
    return page.evaluate(() => {
        Array.from(document.querySelectorAll("script[src]")).forEach(x => {
            x.removeAttribute("async");
            x.setAttribute("defer", "true");
        });
    });
};

const removeScriptTagsWithSrcAttribute = ({ page }) => {
    return page.evaluate(() => {
        Array.from(document.querySelectorAll("script")).filter(node => node.src).forEach(ell => {
            ell.parentElement && ell.parentElement.removeChild(ell);
        });
    });
};

runAsync();
```

**Comment by stereobooster** [comment]
At the moment I'm trying to write proper tests for the package. It was without tests way too long. This means, that all other PRs will be on hold. See #171

**Comment by prasannavl** [comment]
@stereobooster - Hmm. I'd assume that being able to do this removes a lot of maintenance overhead, since it'd provide a pretty neat plugin hook. Anyway, whichever works for you! 

I'm maintaining a fork of this with these two additions, that I rely pretty heavily on -- as different projects have different needs, and this hook provides me with the ability to change things at will without having to touch react-snap directly. So, was hoping to see what your thoughts were on this. Cheers!

**Comment by zheeeng** [comment]
@stereobooster I have a question that how to cleanup dynamically inserted scripts? e.g. Google Analytics script is inserted by calling `document.createEelement('script')` and `document.body.appendChild(script)`, the script is will be inserted in prerendering process and visiting time. I have the only solution is to comment the inserting script prevent prerendering generated the inserted scripts and remove the HTML comment by `postProcess` hook

**Pull request closed without merging**
